# vi: set syntax=yaml ts=4 sw=4 sts=4 et ff=unix ai si :

version: '3'

tasks:
  default:
    desc: Runs the flask app
    silent: true
    cmds:
      - poetry run python flask_app.py

  activate:
    desc: Activates the virtual environment
    silent: true
    cmds:
      - source .venv/bin/activate

  deactivate:
    desc: Deactivates the virtual environment
    silent: true
    cmds:
      - deactivate

